services:
    db:
        image: postgres:17.4
        restart: always
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: senha123
            POSTGRES_DB: ScreenSound
        ports:
            - '5432:5432'
        volumes:
            - pg_data:/var/lib/postfresql/data

volumes:
    pg_data:

# services:
#     db:
#         image: mcr.microsoft.com/mssql/server:2019-latest
#         restart: always
#         environment:
#             ACCEPT_EULA: Y
#             SA_PASSWORD: senha123
#             MSSQL_USER: app
#             MSSQL_DATABASE: ScreenSound
#         ports:
#             - '1433:1433'
#         volumes:
#             - mssql_data:/var/opt/mssql/data

# volumes:
#     mssql_data:
