services:
    db:
        image: postgres:17.4
        restart: always
        environment:
            POSTGRES_USER: app
            POSTGRES_PASSWORD: senha123
            POSTGRES_DB: ScreenSound
        ports:
            - '5432:5432'
        volumes:
            - pg_data:/var/lib/postfresql/data

volumes:
    pg_data:
    